name = "Ggplot2"
uuid = "5eb46db9-241e-4516-b2d9-6a99246a435a"
authors = ["Matt Bhagat-Conway <matt@indicatrix.org> and contributors"]
version = "0.0.1"

[deps]
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"

[compat]
RCall = "0.14.6"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
